---
kind: Service
apiVersion: v1
metadata:
  name:  reviews
spec:
  selector:
    app:  reviews
  type:  ClusterIP
  ports:
  - port:  8080
    targetPort:  8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews
spec:
  selector:
    matchLabels:
      app: reviews
  template:
    metadata:
      labels:
        app: reviews
    spec:
      containers:
      - name: reviews
        image: sharadregoti/reviews:0.1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 8080
