kind: Service
apiVersion: v1
metadata:
  name:  ratings
spec:
  selector:
    app:  ratings
  type:  ClusterIP
  ports:
  - port:  8080
    targetPort:  8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings
spec:
  selector:
    matchLabels:
      app: ratings
  template:
    metadata:
      labels:
        app: ratings
    spec:
      containers:
      - name: ratings
        image: sharadregoti/ratings:0.1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 8080